### PR TITLE
Enter functionality on PatientSearch page

### PR DESCRIPTION
**Pull request by andrewjyang**

### CODE REVIEW

**Comment by mdulin2** [comment]
@andrewjyang. This would be an awesome feature to have! But, let's focus on getting the dispenser functionality working (goal for the week).   
To solve the functionality issue I would shy away from using the Jquery or Javascript within the index.html file. There seems to be an inconsistency with rendering.   

I found this stackoverflow post, that may help? https://stackoverflow.com/questions/33211672/how-to-submit-a-form-using-enter-key-in-react-js

**Comment by jacobkrantz** [comment]
When `first` and `last` fields are both filled, nothing is shown to the user. I think there should be a search that prioritizes one over the other but I don't have a preference which.

**Comment by jacobkrantz** [comment]
The enter button does not work on first load. I have to reload the page and then it works.

**Comment by andrewjyang** [comment]
@mdulin2 wow maxi that link was a wonder hole. patient search now works without having to modify the index.html file. 
@jacobkrantz the new implementation does not require refreshing the page... and if the fields are empty the default is to load the entire table. searching prioritizes id, then first name, then last name.

**Pull request merged**
