### PR TITLE
Updated header component (WIP)

### PR DESCRIPTION
**Pull request by andrewjyang**
- the header component is the navigation bar that appears horizontally on all pages. the navigation bar provides useful shortcuts for navigating throughout our web app.
- it is WIP because the shortcuts that appear need to be custom for each user and user access control is yet to be fully implemented

- added a footer as well

### CODE REVIEW

**Comment by jacobkrantz** [comment]
@andrewjyang what is this PR for? Going forward, if you can provide a summary of changes in the PR description that would help out an outsider like me.

**Comment by andrewjyang** [comment]
> @andrewjyang what is this PR for? Going forward, if you can provide a summary of changes in the PR description that would help out an outsider like me.

provided a summary :)

**Comment by jacobkrantz** [comment]
This PR needs to be on branch Access_Control instead of master

**Comment by andrewjyang** [comment]
The header component is included in access control pr #71

**Pull request closed without merging**
