### PR TITLE
Bootstrap front end with argon; fix front end testing

### PR DESCRIPTION
**Pull request by andrewjyang**

### CODE REVIEW

**Comment by jacobkrantz** [comment]
@andrewjyang from a patient's prescription page, if I hit the back arrow in the browser, the old styling reappears. We should never see the previous style.

**Comment by jacobkrantz** [comment]
@andrewjyang Since the unit test for the front end now works, can we integrate it with Travis? We can open an issue and do this later. How hard should this be? When should we do it?

**Comment by jacobkrantz** [comment]
@andrewjyang When I click on a patient's name to display his or her prescriptions, I am directed to a new tab. I think this is an inconvenience. What is your reasoning for a new tab?

**Comment by jacobkrantz** [comment]
@andrewjyang Back to you! Please address each comment in some capacity:)

**Comment by andrewjyang** [comment]
@jacobkrantz i have committed my changes and addressed all your comments. back to you!

**Pull request merged**
